-- CreateTable
CREATE TABLE IF NOT EXISTS "public"."VenueImages" (
    "id"        INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "venueId"   INT         NOT NULL,
    "url"       TEXT        NOT NULL,
    "alt"       TEXT,
    "position"  INT,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL,

    -- FK (CASCADE)
    CONSTRAINT "VenueImages_venueId_fkey"
         FOREIGN KEY ("venueId")
         REFERENCES public."Venue" ("id")
         ON DELETE CASCADE
         ON UPDATE CASCADE,

    -- Business validation
    CONSTRAINT "chk_venueimages_position_nonnegative"
        CHECK ("position" IS NULL OR "position" >= 0)
);

-- Indexing
CREATE INDEX IF NOT EXISTS "VenueImages_venueId_idx"
    ON public."VenueImages" ("venueId");