-- CreateTable
CREATE TABLE IF NOT EXISTS "public"."Feature" (
    "id"            INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          CITEXT          NOT NULL,
    "createdAt"     timestamptz     NOT NULL DEFAULT now(),
    "updatedAt"     timestamptz     NOT NULL,

    CONSTRAINT "Feature_name_uq" UNIQUE ("name"),

    CONSTRAINT "chk_feature_name_len"
        CHECK (char_length("name") BETWEEN 1 AND 60)
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "public"."VenueFeatures" (
    "venueId"   INT         NOT NULL,
    "featureId" INT         NOT NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "VenueFeatures_pkey" PRIMARY KEY ("venueId","featureId"),

    CONSTRAINT "VenueFeatures_venueId_fkey"
        FOREIGN KEY ("venueId") REFERENCES public."Venue" ("id")
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT "VenueFeatures_featureId_fkey"
        FOREIGN KEY ("featureId") REFERENCES public."Feature" ("id")
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "VenueFeatures_featureId_idx"
    ON public."VenueFeatures" ("featureId");