CREATE EXTENSION IF NOT EXISTS citext;
-- CreateTable
CREATE TABLE IF NOT EXISTS public."VenueAddress"
(
    "id"        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "street"    TEXT        NOT NULL,
    "city"      TEXT        NOT NULL,
    "country"   CHAR(2)     NOT NULL CHECK ("country" ~ '^[A-Z]{2}$'),
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "public"."Venue"
(
    "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title"         TEXT           NOT NULL,
    "slug"          TEXT           NOT NULL UNIQUE,
    "description"   TEXT           NOT NULL,
    "pricePerNight" NUMERIC(10, 2) NOT NULL CHECK ("pricePerNight" >= 0),
    "capacity"      INTEGER        NOT NULL CHECK ("capacity" > 0),
    "latitude"      DOUBLE PRECISION,
    "longitude"     DOUBLE PRECISION,
    "addressId"     INT UNIQUE REFERENCES public."VenueAddress" ("id")
        ON DELETE SET NULL ON UPDATE CASCADE, -- FK inline,
    "hostId"        INT            NOT NULL REFERENCES public."User" ("id")
        ON DELETE RESTRICT ON UPDATE CASCADE, -- FK inline,
    "createdAt"     timestamptz    NOT NULL DEFAULT now(),
    "updatedAt"     timestamptz    NOT NULL
);


-- For filtering
CREATE INDEX IF NOT EXISTS "Venue_hostId_idx" ON public."Venue" ("hostId");
CREATE INDEX IF NOT EXISTS "Venue_pricePerNight_idx" ON public."Venue" ("pricePerNight");
CREATE INDEX IF NOT EXISTS "Venue_capacity_idx" ON public."Venue" ("capacity");
CREATE INDEX IF NOT EXISTS "Venue_host_price_idx" ON public."Venue" ("hostId", "pricePerNight");