CREATE
EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS public."User"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email"       CITEXT      NOT NULL,
    "name"        TEXT        NOT NULL,
    "password"    TEXT        NOT NULL,
    "phoneNumber" TEXT,
    "createdAt"   timestamptz NOT NULL DEFAULT now(),
    "updatedAt"   timestamptz NOT NULL
);

CREATE UNIQUE INDEX "User_email_key" ON public."User" ("email");
CREATE INDEX "User_createdAt_idx" ON public."User" ("createdAt");

CREATE TABLE IF NOT EXISTS public."Address"
(
    "userId"    INT         NOT NULL PRIMARY KEY,
    "street"    TEXT        NOT NULL,
    "city"      TEXT        NOT NULL,
    "country"   CHAR(2)     NOT NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL
);

ALTER TABLE public."Address"
    ADD CONSTRAINT "Address_userId_fkey"
        FOREIGN KEY ("userId") REFERENCES public."User" ("id")
            ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE public."Address"
    ADD CONSTRAINT country_is_upper CHECK ("country" ~ '^[A-Z]{2}$');

