-- Add new columns to Venue
ALTER TABLE "public"."Venue"
    ADD COLUMN "albumId" INTEGER,
    ADD COLUMN "rating" DOUBLE PRECISION;

-- Add postalCode to VenueAddress
ALTER TABLE "public"."VenueAddress"
    ADD COLUMN "postalCode" TEXT;

-- Create VenueDetails table (1-1 with Venue)
CREATE TABLE "public"."VenueDetails"
(
    "id"                         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "venueId"                    INTEGER NOT NULL,
    "numberOfReviews"            INTEGER NOT NULL DEFAULT 0,
    "checkInHour"                TEXT,
    "checkOutHour"               TEXT,
    "distanceFromCityCenterInKM" INTEGER,
    "sleepingMaxCapacity"        INTEGER,
    "sleepingBeds"               INTEGER,
    "contactEmail"               TEXT,
    "contactPhone"               TEXT
);

-- Ensure 1-1: one details row per venue
CREATE UNIQUE INDEX "VenueDetails_venueId_key" ON "public"."VenueDetails" ("venueId");

-- FK with cascade to auto-clean details when venue is deleted
ALTER TABLE "public"."VenueDetails"
    ADD CONSTRAINT "VenueDetails_venueId_fkey"
        FOREIGN KEY ("venueId") REFERENCES "public"."Venue" ("id")
            ON DELETE CASCADE ON UPDATE CASCADE;